- name: Flake8 action
  # You may pin to the exact commit or the version.
  # uses: suo/flake8-github-action@3e87882219642e01aa8a6bbd03b4b0adb8542c2a
  uses: suo/flake8-github-action@v1
  with:
    # The name of the check to add annotations to.
Generally the same as the job that uses this action
    checkName: 
