name: Lint

on:
  workflow_dispatch:
    branches:
      - main
      - '2020'
  push:
    branches:
      - main
      - '2020'
    paths:
      - '**.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
          architecture: x64

      - name: Install flake8
        run: pip install flake8

      - name: Test
        run: echo test

      - name: Run flake8
        run: flake8
